### ISSUE TITLE
macOS: Disable titlebar but keep rounded corners

### ISSUE THREAD

**Issue by cwqt** [wez/wezterm#1034]
**Is your feature request related to a problem? Please describe.**
Currently `window_decorations` `TITLE` hides not only the titlebar but all other window decorations

**Describe the solution you'd like**
Extend `window_decorations` to allow hiding of titlebar decoration while keeping rounded corners, see pic, bottom is kitty & top is wezterm

in kitty it's possible to keep the corner decorations via:

```
hide_window_decorations titlebar-only
```

<img width="852" alt="Screenshot 2021-08-16 at 22 37 36" src="https://user-images.githubusercontent.com/61694629/129632707-145a6892-50b2-4acb-83f8-785b47c6918b.png">

**Comment by wez** [comment]
Did you try `window_decorations = "RESIZE"` ?

**Comment by nklmilojevic** [comment]
Just got into the same issue, I have tried resize as window_decorations on macos but it is still not a rounded corner.

**Comment by nklmilojevic** [comment]
@wez can you reopen this one?

**Comment by cwqt** [comment]
Sorry forgot about this one, & yes `RESIZE` has no effect

<img width="863" alt="Screenshot 2021-11-28 at 4 28 02 pm" src="https://user-images.githubusercontent.com/61694629/143776947-39ecd1d0-2292-40b5-ab06-3662fd019716.png">

**Comment by nklmilojevic** [comment]
Any idea where is this coming from? I'd gladly help with a PR if you just point me where to look :)

**Comment by wez** [comment]
I would gladly accept a PR for this!

All we do is apply a style mask based on the requested decorations:

https://github.com/wez/wezterm/blob/main/window/src/os/macos/window.rs#L713-L717

(there are a couple of places that call `decoration_to_mask` in there that do similar but slightly different things in different contexts,)

I haven't had the time to dig into why that stops the corners being rounded... I would suggest stackoverflow/google searching, and/or taking a peek in the kitty code (which might just delegate through glfw) to see how it makes this work!

**Comment by nklmilojevic** [comment]
Thanks! I will also check at Alacritty because it has rounded edges.

**Comment by nklmilojevic** [comment]
My rust is rusty (😅) but shouldn't we add https://docs.rs/cocoa/0.20.2/cocoa/appkit/enum.NSWindowTitleVisibility.html somewhere?

**Comment by nklmilojevic** [comment]
![CleanShot 2021-12-08 at 18 50 56@2x](https://user-images.githubusercontent.com/9573356/145258339-9be7fb0d-1e73-409b-9505-038fd07a2593.png)


Getting there...

**Comment by nklmilojevic** [comment]
Ok, here we go:

![CleanShot 2021-12-08 at 19 04 59@2x](https://user-images.githubusercontent.com/9573356/145260397-85047559-2046-4420-83a5-2840190d845d.png)

@wez as this is my first time diving into Rust, I don't want to submit PR as it is spaghetti code, but I can tell you what I added in order for this to work:

On line 468 of window.rs

```
            for titlebar_button in &[
                appkit::NSWindowButton::NSWindowFullScreenButton,
                appkit::NSWindowButton::NSWindowMiniaturizeButton,
                appkit::NSWindowButton::NSWindowCloseButton,
                appkit::NSWindowButton::NSWindowZoomButton,
            ] {
                let button = window.standardWindowButton_(*titlebar_button);
                let _: () = msg_send![button, setHidden: YES];
            }
            window.setTitleVisibility_(appkit::NSWindowTitleVisibility::NSWindowTitleHidden);
            window.setTitlebarAppearsTransparent_(YES);
```

and changed windows decorations for resize like this:

```
    } else if decorations == WindowDecorations::RESIZE {
        NSWindowStyleMask::NSClosableWindowMask
            | NSWindowStyleMask::NSMiniaturizableWindowMask
            | NSWindowStyleMask::NSResizableWindowMask
            | NSWindowStyleMask::NSTitledWindowMask
            | NSWindowStyleMask::NSFullSizeContentViewWindowMask
```

Seems that in order to keep the rounded windows you have to use TitledWindowMask together with FulSizeContentViewWindowMask and then to set Titlebar to transparent and remove the buttons.

Let me know if you can implement this, I'll be running my spaghetti local build until then :)

**Comment by wez** [comment]
Thanks; I can run with this!

**Comment by wez** [comment]
This is fixed in the nightly builds; please give it a try and let me know how you get on!

**Comment by tdjordan** [comment]
I know this is closed but is there a way to have a configuration that removes the rounded corners?

**Comment by nklmilojevic** [comment]
```
local wezterm = require("wezterm")

return {
    font = wezterm.font_with_fallback(
        {
            "PragmataProMonoLiga Nerd Font"
        }
    ),
    window_decorations = "RESIZE",
    font_size = 16.0,
    font_antialias = "Subpixel",
    color_scheme = "Dracula",
    enable_tab_bar = false,
    send_composed_key_when_left_alt_is_pressed = true,
    send_composed_key_when_right_alt_is_pressed = true,
    window_padding = {
        left = 10,
        right = 10,
        top = 10,
        bottom = 10
    }
}
```

This is what I use, the important part is `window_decorations = "RESIZE"`.

**Comment by tdjordan** [comment]
I do have that setting — and yet, I am still getting the rounded corners.

I want to reproduce the same behavior as Alarcitty's `decoration = NONE` setting.

Here is what my current settings are — please ignore the commented-out fonts ...    I have been trying to get the font settings to work the way I want also.

Note, that when I tried to set `window_decorations = "NONE"`, I started to get some weird behavior
* The `adjust_window_size_when_changing_font_size = false` stopped working as expected with my Tiling Window Manager `yabai`

```
local wt = require 'wezterm'

local font_with_fallback = function( name, params )
  local names = {
    name
    , 'Noto Color Emoji'
    , 'JetBrains Mono'
  }
  return wt.font_with_fallback( names, params )
end

return {
  adjust_window_size_when_changing_font_size = false
  , hide_tab_bar_if_only_one_tab = true
  -- , color_scheme = 'Batman'
  -- , color_scheme = 'Medallion'
  -- , color_scheme = 'Gruvbox Dark'
  -- , color_scheme = 'Brogrammer'
  -- , color_scheme = 'Builtin Pastel Dark'
  , color_scheme = 'Abernathy'
  , font_rules = {
    ---  normal
    ---
    {
      italic = false
      -- , intensity = 'Bold'
      , font = wt.font_with_fallback {
        -- 'Source Code Pro',
        -- 'SauceCodePro Nerd Font Mono',
        -- 'NotoMono Nerd Font Mono',
        -- 'FiraCode Nerd Font',
        -- 'NotoMono Nerd Font',
        -- 'JetBrains Mono',
        -- 'VictorMono Nerd Font Mono',
        -- 'Hack Nerd Font Mono',
        'FiraCode Nerd Font Mono',
        -- 'Symbols Nerd Font Mono'
      -- , font = wt.font {
      --   family = 'FiraCode Nerd Font',
        -- family = 'VictorMono Nerd Font Mono',
        -- weight = 'Regular',
        -- stretch = 'Normal',
        -- italic = false
      }
    },

    ---  normal
    ---
    {
      italic = false
      , intensity = 'Bold'
      , font = wt.font_with_fallback {
        -- 'Hack Nerd Font Mono',
        'VictorMono Nerd Font Mono',
        -- 'Symbols Nerd Font Mono'
        -- family = 'VictorMono Nerd Font Mono',
        -- weight = 'Bold',
        -- stretch = 'Normal',
        -- italic = false
      }
    },

    ---  bold
    ---
    -- {
    --   italic = false
    --   , intensity = 'Bold'
    --   , font = font_with_fallback 'VictorMono Nerd Font Mono'
    -- },

    ---  italic
    ---
    -- {
    --   italic = true
    --   , font = wt.font(
    --       {
    --         family = 'VictorMono Nerd Font Mono',
    --         italic = true
    --       },
    --       { family = 'Noto Color Emoji', italic = true },
    --       { family = 'JetBrains Mono'  , italic = true }
    --     )
    -- },
    -- {
    --   italic = true,
    --   font = wt.font( 'VictorMono Nerd Font Mono', { italic = true } )
    -- },
    -- {
    --   italic = true,
    --   font = wt.font {
    --     family = 'VictorMono Nerd Font Mono',
    --     italic = true
    --   }
    -- },

    ---  bold italic
    ---
    -- {
    --   italic = true
    --   , intensity = 'Bold'
    --   , font = font_with_fallback(
    --     'VictorMono Nerd Font Mono',
    --     { italic = true }
    --   )
    -- }
  }
  -- , font = wt.font {
  --   family = 'VictorMono Nerd Font Mono',
  --   stretch = 'Expanded',
  --   italic = true
  -- }
  -- , font = wt.font {
  --   family = 'FiraCode Nerd Font',
  --   stretch = 'Expanded',
  --   -- italic = true
  -- }
  -- , font = wt.font( 'FiraCode Nerd Font', { weight = 'Regular' } )
  -- , font = wt.font 'JetBrains Mono'
  -- , font = wt.font 'VictorMono Nerd Font'
  , font_size = 17.0
  , enable_tab_bar = false
  -- , tab_bar_at_bottom = true
  , window_decorations = 'RESIZE'
  -- , window_decorations = 'NONE'
  , window_padding = {
    left = 0
    , right = 0
    , top = 0
    , bottom = 0
  }
  -- , enable_scroll_bar = false
  , use_fancy_tab_bar = false
  , term = 'wezterm'
}
```
