### ISSUE TITLE
Wezterm briefly gives incorrect size at launch

### ISSUE THREAD

**Issue by Anomalocaridid** [wez/wezterm#1115]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### WezTerm version

wezterm 20210906-110516-86f0bae1

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When I launch WezTerm in Sway and if its window does not take up the whole workspace, then zsh gets an inaccurate column count briefly at launch. I do not have this issue when using another terminal such as xfce4-terminal.

### To Reproduce

Linux Distro: EndeavourOS Sway
Shell: zsh 5.8 (x86_64-pc-linux-gnu)

1. In a .zshrc put the following code at or near the top:

```
echo $(tput cols)
sleep 1
echo $(tput cols)
```
Open WezTerm in Sway, with tiling set to vertical and at least one other window of any kind already open in the same workspace.

Both commands should output different numbers of columns, despite the window not visibly changing. The sleep command gives the terminal a generous amount of time to catch up so that the second command outputs a more accurate number. Running the same commands after the shell's startup will give the expected results.

### Configuration

no config

### Expected Behavior

I expected the number of columns reported to not change or at least to change quickly enough that it would not affect any command ran on terminal startup.

### Logs

21:31:14.550 INFO wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-124555
21:31:14.605 INFO wezterm_gui::termwindow > OpenGL initialized! Radeon RX 580 Series (POLARIS10, DRM 3.41.0, 5.13.13-arch1-1, LLVM 12.0.1) 4.6 (Compatibility Profile) Mesa 21.2.1 is_context_loss_possible=false wezterm version: 20210906-110516-86f0bae1
21:35:00.042 WARNING wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(1)
21:35:00.042 WARNING wezterm_term::terminalstate::performer > unknown unspecified CSI: "22t"
21:35:29.212 WARNING wezterm_term::terminalstate::performer > unknown unspecified CSI: "23t"
21:35:29.212 WARNING wezterm_term::terminalstate > unhandled XtermKeyMode OtherKeys Some(0)
21:35:33.128 INFO wezterm_gui::frontend > Ding! (this is the bell)

### Anything else?

This affects other commands that rely on the terminal's number of columns, such as `toilet -t`. Toilet is a program that turns text into large ASCII art text, similar to figlet, and the -t flag makes its output fit to the terminal's width.

**Comment by wez** [comment]
Please try the latest nightly; it's possible that this was fixed by #1112

**Comment by Anomalocaridid** [comment]
Sorry for taking so long to get back to you. I have installed what I believe is currently the latest WezTerm nightly build: wezterm 20210919-182757-8f0ab02b. My problem does not appear to be resolved.

**Comment by wez** [comment]
Could you try the latest nightly? There have been a couple more fixes around startup window size and updating the size in the pty that may have resolved this

**Comment by Anomalocaridid** [comment]
The nightly resolved it, but only when the terminal's opened in an empty workspace or in a workspace where the only window is a tabbed container.

It's still a significant improvement and I appreciate you letting me know about the recent fixes.

**Comment by tavisrudd** [comment]
This is still happening in wezterm nightly on sway wm if the workspace already has other windows on it. It's also affecting the rendering of background images / transparency and what stty size reports until a resize or focus event on the window triggers an update. I'm working around it with a wrapper script that toggles focus briefly when launching the new wezterm window.

**Comment by tavisrudd** [comment]
Possibly the same issue in #7156.
