### ISSUE TITLE
sixel doesn't work on Windows 10

### ISSUE THREAD

**Issue by xiangpeng2008** [wez/wezterm#1236]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20210814-124438-54e29167

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

when I open wezterm on windows10, ssh to remote linux, and `img2sixel path/img.png`, nothing prints

### To Reproduce

open wezterm on windows10
ssh to linux server
`img2sixel path/img.png`

![image](https://user-images.githubusercontent.com/15676035/137626632-94ab1c04-f855-4289-a2f1-5818f01ff49b.png)

### Configuration

no config

### Expected Behavior

Sixel graphics support (experimental: starting in 20200620-160318-e00b076c)

### Logs
```
 2021-10-17T12:07:17.919Z INFO  wezterm_mux_server_impl::local > setting up C:\Users\zhangxia\.local/share/wezterm\gui-sock-6796
 2021-10-17T12:07:18.484Z WARN  wezterm_term::terminalstate    > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(9001))
 2021-10-17T12:07:18.960Z INFO  wezterm_gui::termwindow        > OpenGL initialized! ANGLE (NVIDIA Quadro P620 Direct3D11 vs_5_0 ps_5_0) OpenGL ES 3.0.0 (ANGLE 2.1.1 git hash: 07ea804e6201) is_context_loss_possible=true wezterm version: 20210814-124438-54e29167
 2021-10-17T12:07:30.103Z WARN  wezterm_term::terminalstate    > unhandled DecPrivateMode SetDecPrivateMode(Unspecified(1034))
```

**Comment by wez** [comment]
We're waiting on some combination of:
https://github.com/microsoft/terminal/issues/1173
https://github.com/microsoft/terminal/issues/448

before this will work directly on ConPTY

**Comment by ykhan21** [comment]
For what it's worth, [mintty](https://mintty.github.io/) is a Windows terminal that supports sixel graphics.

**Comment by wez** [comment]
@ykhan21 wezterm *does* support sixel graphics. It's conpty in the middle that can mess things up

**Comment by wez** [comment]
The workaround that I suggest is using `wezterm ssh` to get directly into eg: a WSL environment or a remote linux environment

**Comment by ykhan21** [comment]
Is there a way to get it to work without ssh-ing into a linux / WSL environment? For example, on Windows I can use imagemagick to generate sixel graphics.

**Comment by wez** [comment]
No, conpty, which is intimately tied to native console program output on windows, does not support sixels.
To use sixel, you need to avoid conpty.
Learn more about conpty: https://wezfurlong.org/wezterm/what-is-a-terminal.html#windows-and-conpty

As an alternative, using the iTerm2 image protocol using a different kind of escape sequence that can mostly squeeze through conpty.

Consider using eg: png or jpg images together with [wezterm imgcat](https://wezfurlong.org/wezterm/cli/imgcat.html)

**Comment by AnonymouX47** [comment]
I think this might be worth looking into, now that https://github.com/microsoft/terminal/issues/1173 has been resolved.

Thanks.

**Comment by pcgeek86** [comment]
Now that Microsoft Windows Terminal (Preview) supports sixel, is there any reason that conpty would still block wezterm support for sixel?

This screenshot shows wezterm running side-by-side with Windows Terminal Preview. Windows Terminal can render sixel graphics, but wezterm still cannot.

![image](https://github.com/user-attachments/assets/57a9a48d-2c06-4ea7-ba41-84631628f66c)

I have very little to no knowledge on terminal architecture, so it isn't clear to me why one works, but not the other. So, be gentle in your responses. :)

**Comment by AnonymouX47** [comment]
> So, be gentle in your responses. :) 

I just want to say... as far as I know, he always is. :smiley:

**Comment by a-usr** [comment]
Hello, today I noticed that miraculously both sixel and kitty support randomly started working. This is difficult to explain for me, since I didnt update anything, and Windows Update claims to not have done anything like that either. However I suppose that isnt that important, I just thought I'd let yall know.

![Image](https://github.com/user-attachments/assets/25f47e52-b7d6-474a-966e-c4189d8e3c59)

**Comment by Kreijstal** [comment]
> Hello, today I noticed that miraculously both sixel and kitty support randomly started working. This is difficult to explain for me, since I didnt update anything, and Windows Update claims to not have done anything like that either. However I suppose that isnt that important, I just thought I'd let yall know.
> 
> ![Image](https://github.com/user-attachments/assets/25f47e52-b7d6-474a-966e-c4189d8e3c59)

is this ssh wezterm, or wezterm under windows? 
ssh wezterm does support sixel, but if you use wezterm then use ssh, it won't work, are you sure?

which windows version do you use and which wezterm version is this?

**Comment by a-usr** [comment]
this is on Windows 11 build 22631.4751, with wezterm nightly (`wezterm 20250210-070846-3bc67e44`). Both mentioned image protocols work both using the unix domain, and the local one. SSH wasnt used, this should go through regular conPTY.

**Comment by a-usr** [comment]
Also uhh this

![Image](https://github.com/user-attachments/assets/bc4ccb9c-2ce9-4486-bb1c-8ce961491eb9)

I can assure you, the image is *not* black

**Comment by wez** [comment]
Thank you for confirming that it works!
