### ISSUE TITLE
Cannot render this glyph format on non-HiDPI display

### ISSUE THREAD

**Issue by maximko** [wez/wezterm#1419]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20211218-094600-ea46967e

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

After upgrading from 20210814-124438,54e29167 to 20211205-192649,672c1cc1 wezterm becomes totally unusable on my external FullHD display. Same with latest nightly version. It works fine on mbp's retina display, as well as on external display with empty config. 
![Screenshot 2021-12-19 at 17 23 53](https://user-images.githubusercontent.com/633363/146678342-29d6a932-3582-4e72-abaf-34e826877000.png)

### Configuration

```lua
local wezterm = require 'wezterm';

return {
  font = wezterm.font("Monaco"),
  font_rules={
    {
      intensity="Bold",
      font=wezterm.font("Monaco", {
        foreground="#ffffff",
        weight="Bold"
      })
    },
    {
      italic=true,
      font=wezterm.font("Monaco", {
        italic=true
      })
    },
  },
  font_size = 14.0,
  color_scheme = "iterm",
  scrollback_lines = 15000,
  tab_max_width = 32,
  harfbuzz_features = {"calt=0", "clig=0", "liga=0"},
  bypass_mouse_reporting_modifiers = "ALT",
}
```

### Logs

17:19:10.797 INFO wezterm_mux_server_impl::local > setting up /Users/maxi/.local/share/wezterm/gui-sock-19113
17:19:10.940 INFO wezterm_gui::termwindow > OpenGL initialized! AMD Radeon Pro 5300M OpenGL Engine 4.1 ATI-3.10.22 is_context_loss_possible=false wezterm version: 20211218-094600-ea46967e
17:19:10.940 WARNING wezterm_term::terminalstate::performer > Unhandled OSC  1337 RemoteHost=maxi@m16.home.arpa
17:19:10.995 WARNING wezterm_term::terminalstate::performer > unhandled iterm2:CurrentDir("/Users/maxi")
17:19:10.995 WARNING wezterm_term::terminalstate::performer > Unhandled OSC  1337 ShellIntegrationVersion=16 shell=bash
17:19:11.034 WARNING wezterm_term::terminalstate::performer > Unhandled OSC  1337 RemoteHost=maxi@m16.home.arpa
17:19:11.034 WARNING wezterm_term::terminalstate::performer > unhandled iterm2:CurrentDir("/Users/maxi")
17:19:11.041 ERROR wezterm_gui::glyphcache > load_glyph failed; using blank instead. Error: load_and_render_glyph: FT_Render_Glyph: FreeType error 19 0x13: cannot render this glyph format. GlyphInfo { is_space: false, cluster: 9, font_idx:0, glyph_pos: 85, x_advance: 8.0, y_advance: 0.0, x_offset: 0.0, y_offset: 0.0 } TextStyle { font: [FontAttributes { family: "Monaco", weight: FontWeight(400),stretch: Normal, italic: false, is_fallback: false, is_synthetic: false }], foreground: None }
17:19:11.041 ERROR wezterm_gui::glyphcache > load_glyph failed; using blank instead. Error: load_and_render_glyph: FT_Render_Glyph: FreeType error 19 0x13: cannot render this glyph format. GlyphInfo { is_space: false, cluster: 10, font_idx: 0, glyph_pos: 80, x_advance: 8.0, y_advance: 0.0, x_offset: 0.0, y_offset: 0.0} TextStyle { font: [FontAttributes { family: "Monaco", weight: FontWeight(400), stretch: Normal, italic: false, is_fallback: false, is_synthetic: false }], foreground: None }
17:19:11.041 ERROR wezterm_gui::glyphcache > load_glyph failed; using blank instead. Error: load_and_render_glyph: FT_Render_Glyph: FreeType error 19 0x13: cannot render this glyph format. GlyphInfo { is_space: false, cluster: 1, font_idx:0, glyph_pos: 14, x_advance: 8.0, y_advance: 0.0, x_offset: 0.0, y_offset: 0.0 } TextStyle { font: [FontAttributes { family: "Monaco", weight: FontWeight(400),stretch: Normal, italic: false, is_fallback: false, is_synthetic: false }], foreground: None }
>

### Anything else?

macOS 10.15.7

**Comment by wez** [comment]
Does it start/stop rendering correctly if you drag the window between the internal retina and the external display?

Please run: `wezterm ls-fonts` and attach the output here.

Then try starting wezterm like this:

```
WEZTERM_LOG=wezterm_gui::termwindow=trace,wezterm_gui::termwindow::render=info,info wezterm
```

and share the log output; it should show a few lines that look something like this, although this output is from my linux system:

```
 2021-12-19T14:39:01.136Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-1989118
 2021-12-19T14:39:01.195Z TRACE wezterm_gui::termwindow        > using render_metrics RenderMetrics {
    descender: -4.0,
    descender_row: 14,
    descender_plus_two: 15,
    underline_height: 1,
    strike_row: 7,
    cell_size: 8x16,
}
 2021-12-19T14:39:01.363Z TRACE wezterm_gui::termwindow        > TermWindow::new_window called with mux_window_id 0 PtySize { rows: 24, cols: 80, pixel_width: 640, pixel_height: 384 } Dimensions { pixel_width: 656, pixel_height: 438, dpi: 96 }
 2021-12-19T14:39:01.481Z TRACE wezterm_gui::termwindow        > Setting focus to true
 2021-12-19T14:39:01.501Z INFO  wezterm_gui::termwindow        > OpenGL initialized! NVIDIA GeForce GT 1030/PCIe/SSE2 4.6.0 NVIDIA 495.44 is_context_loss_possible=false wezterm version: 20211219-063039-9e9e76bf
```

Then, please try a different font to see if this is specific to the Monaco font!

**Comment by maximko** [comment]
> Does it start/stop rendering correctly if you drag the window between the internal retina and the external display?

Yep

`wezterm ls-fonts` log:
```
Primary font:
wezterm.font_with_fallback({
  -- /System/Library/Fonts/Monaco.dfont, CoreText
  -- Pixel sizes: [12, 13, 16, 19]
  "Monaco",

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Bold:
wezterm.font_with_fallback({
  -- /System/Library/Fonts/Monaco.dfont, CoreText
  -- Will synthesize bold
  -- Pixel sizes: [12, 13, 16, 19]
  "Monaco",

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Italic=true:
wezterm.font_with_fallback({
  -- /System/Library/Fonts/Monaco.dfont, CoreText
  -- Will synthesize italics
  -- Pixel sizes: [12, 13, 16, 19]
  "Monaco",

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Half Italic=true:
wezterm.font_with_fallback({
  -- /System/Library/Fonts/Monaco.dfont, CoreText
  -- Will synthesize italics
  -- Will synthesize dim
  -- Pixel sizes: [12, 13, 16, 19]
  "Monaco",

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Half Italic=false:
wezterm.font_with_fallback({
  -- /System/Library/Fonts/Monaco.dfont, CoreText
  -- Will synthesize dim
  -- Pixel sizes: [12, 13, 16, 19]
  "Monaco",

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Bold Italic=false:
wezterm.font_with_fallback({
  -- /System/Library/Fonts/Monaco.dfont, CoreText
  -- Pixel sizes: [12, 13, 16, 19]
  "Monaco",

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Bold Italic=true:
wezterm.font_with_fallback({
  -- /System/Library/Fonts/Monaco.dfont, CoreText
  -- Will synthesize italics
  -- Pixel sizes: [12, 13, 16, 19]
  "Monaco",

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Normal Italic=true:
wezterm.font_with_fallback({
  -- /System/Library/Fonts/Monaco.dfont, CoreText
  -- Will synthesize italics
  -- Pixel sizes: [12, 13, 16, 19]
  "Monaco",

  -- <built-in>, BuiltIn
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})
```
> `WEZTERM_LOG=wezterm_gui::termwindow=trace,wezterm_gui::termwindow::render=info,info wezterm`

```
 2021-12-19T14:47:12.377Z INFO  wezterm_mux_server_impl::local > setting up /Users/maxi/.local/share/wezterm/gui-sock-20427
 2021-12-19T14:47:12.452Z TRACE wezterm_gui::termwindow        > using render_metrics RenderMetrics {
    descender: -4.0,
    descender_row: 16,
    descender_plus_two: 18,
    underline_height: 1,
    strike_row: 8,
    cell_size: 8x19,
}
 2021-12-19T14:47:12.453Z TRACE wezterm_gui::termwindow        > Initial geometry was PtySize { rows: 24, cols: 80, pixel_width: 640, pixel_height: 456 } but dpi-adjusted geometry is PtySize { rows: 24, cols: 80, pixel_width: 640, pixel_height: 384 }; update the kernel pixel geometry for the ptys!
 2021-12-19T14:47:12.453Z TRACE wezterm_gui::termwindow        > TermWindow::new_window called with mux_window_id 0 PtySize { rows: 24, cols: 80, pixel_width: 640, pixel_height: 456 } Dimensions { pixel_width: 656, pixel_height: 493, dpi: 72 }
 2021-12-19T14:47:12.472Z TRACE wezterm_gui::termwindow::resize > resize event, current cells: RowsAndCols { rows: 24, cols: 80 }, current dims: Dimensions { pixel_width: 656, pixel_height: 493, dpi: 72 }, new dims: Dimensions { pixel_width: 656, pixel_height: 493, dpi: 72 } window_state:(empty)
 2021-12-19T14:47:12.472Z TRACE wezterm_gui::termwindow::resize > dimensions didn't change NOP!
 2021-12-19T14:47:12.523Z WARN  wezterm_term::terminalstate::performer > Unhandled OSC  1337 RemoteHost=maxi@m16.home.arpa
 2021-12-19T14:47:12.528Z INFO  wezterm_gui::termwindow                > OpenGL initialized! AMD Radeon Pro 5300M OpenGL Engine 4.1 ATI-3.10.22 is_context_loss_possible=false wezterm version: 20211218-094600-ea46967e
 2021-12-19T14:47:12.529Z WARN  wezterm_term::terminalstate::performer > unhandled iterm2: CurrentDir("/Users/maxi")
 2021-12-19T14:47:12.529Z WARN  wezterm_term::terminalstate::performer > Unhandled OSC  1337 ShellIntegrationVersion=16 shell=bash
 2021-12-19T14:47:12.531Z WARN  wezterm_term::terminalstate::performer > Unhandled OSC  1337 RemoteHost=maxi@m16.home.arpa
 2021-12-19T14:47:12.536Z WARN  wezterm_term::terminalstate::performer > unhandled iterm2: CurrentDir("/Users/maxi")
 2021-12-19T14:47:12.550Z ERROR wezterm_gui::glyphcache                > load_glyph failed; using blank instead. Error: load_and_render_glyph: FT_Render_Glyph: FreeType error 19 0x13: cannot render this glyph format. GlyphInfo { is_space: false, cluster: 0, font_idx: 0, glyph_pos: 80, x_advance: 8.0, y_advance: 0.0, x_offset: 0.0, y_offset: 0.0 } TextStyle { font: [FontAttributes { family: "Monaco", weight: FontWeight(400), stretch: Normal, italic: false, is_fallback: false, is_synthetic: false }], foreground: None }
 2021-12-19T14:47:12.550Z ERROR wezterm_gui::glyphcache                > load_glyph failed; using blank instead. Error: load_and_render_glyph: FT_Render_Glyph: FreeType error 19 0x13: cannot render this glyph format. GlyphInfo { is_space: false, cluster: 1, font_idx: 0, glyph_pos: 20, x_advance: 8.0, y_advance: 0.0, x_offset: 0.0, y_offset: 0.0 } TextStyle { font: [FontAttributes { family: "Monaco", weight: FontWeight(400), stretch: Normal, italic: false, is_fallback: false, is_synthetic: false }], foreground: None }
 2021-12-19T14:47:12.550Z ERROR wezterm_gui::glyphcache                > load_glyph failed; using blank instead. Error: load_and_render_glyph: FT_Render_Glyph: FreeType error 19 0x13: cannot render this glyph format. GlyphInfo { is_space: false, cluster: 2, font_idx: 0, glyph_pos: 25, x_advance: 8.0, y_advance: 0.0, x_offset: 0.0, y_offset: 0.0 } TextStyle { font: [FontAttributes { family: "Monaco", weight: FontWeight(400), stretch: Normal, italic: false, is_fallback: false, is_synthetic: false }], foreground: None }
 2021-12-19T14:47:12.550Z ERROR wezterm_gui::glyphcache                > load_glyph failed; using blank instead. Error: load_and_render_glyph: FT_Render_Glyph: FreeType error 19 0x13: cannot render this glyph format. GlyphInfo { is_space: false, cluster: 3, font_idx: 0, glyph_pos: 29, x_advance: 8.0, y_advance: 0.0, x_offset: 0.0, y_offset: 0.0 } TextStyle { font: [FontAttributes { family: "Monaco", weight: FontWeight(400), stretch: Normal, italic: false, is_fallback: false, is_synthetic: false }], foreground: None }
 2021-12-19T14:47:12.550Z ERROR wezterm_gui::glyphcache                > load_glyph failed; using blank instead. Error: load_and_render_glyph: FT_Render_Glyph: FreeType error 19 0x13: cannot render this glyph format. GlyphInfo { is_space: false, cluster: 4, font_idx: 0, glyph_pos: 97, x_advance: 8.0, y_advance: 0.0, x_offset: 0.0, y_offset: 0.0 } TextStyle { font: [FontAttributes { family: "Monaco", weight: FontWeight(400), stretch: Normal, italic: false, is_fallback: false, is_synthetic: false }], foreground: None }
 2021-12-19T14:47:12.550Z ERROR wezterm_gui::glyphcache                > load_glyph failed; using blank instead. Error: load_and_render_glyph: FT_Render_Glyph: FreeType error 19 0x13: cannot render this glyph format. GlyphInfo { is_space: true, cluster: 5, font_idx: 0, glyph_pos: 3, x_advance: 8.0, y_advance: 0.0, x_offset: 0.0, y_offset: 0.0 } TextStyle { font: [FontAttributes { family: "Monaco", weight: FontWeight(400), stretch: Normal, italic: false, is_fallback: false, is_synthetic: false }], foreground: None }
 2021-12-19T14:47:12.550Z ERROR wezterm_gui::glyphcache                > load_glyph failed; using blank instead. Error: load_and_render_glyph: FT_Render_Glyph: FreeType error 19 0x13: cannot render this glyph format. GlyphInfo { is_space: false, cluster: 7, font_idx: 0, glyph_pos: 68, x_advance: 8.0, y_advance: 0.0, x_offset: 0.0, y_offset: 0.0 } TextStyle { font: [FontAttributes { family: "Monaco", weight: FontWeight(400), stretch: Normal, italic: false, is_fallback: false, is_synthetic: false }], foreground: None }
 2021-12-19T14:47:12.550Z ERROR wezterm_gui::glyphcache                > load_glyph failed; using blank instead. Error: load_and_render_glyph: FT_Render_Glyph: FreeType error 19 0x13: cannot render this glyph format. GlyphInfo { is_space: false, cluster: 8, font_idx: 0, glyph_pos: 91, x_advance: 8.0, y_advance: 0.0, x_offset: 0.0, y_offset: 0.0 } TextStyle { font: [FontAttributes { family: "Monaco", weight: FontWeight(400), stretch: Normal, italic: false, is_fallback: false, is_synthetic: false }], foreground: None }
 2021-12-19T14:47:12.550Z ERROR wezterm_gui::glyphcache                > load_glyph failed; using blank instead. Error: load_and_render_glyph: FT_Render_Glyph: FreeType error 19 0x13: cannot render this glyph format. GlyphInfo { is_space: false, cluster: 9, font_idx: 0, glyph_pos: 76, x_advance: 8.0, y_advance: 0.0, x_offset: 0.0, y_offset: 0.0 } TextStyle { font: [FontAttributes { family: "Monaco", weight: FontWeight(400), stretch: Normal, italic: false, is_fallback: false, is_synthetic: false }], foreground: None }
 2021-12-19T14:47:12.550Z ERROR wezterm_gui::glyphcache                > load_glyph failed; using blank instead. Error: load_and_render_glyph: FT_Render_Glyph: FreeType error 19 0x13: cannot render this glyph format. GlyphInfo { is_space: false, cluster: 10, font_idx: 0, glyph_pos: 7, x_advance: 8.0, y_advance: 0.0, x_offset: 0.0, y_offset: 0.0 } TextStyle { font: [FontAttributes { family: "Monaco", weight: FontWeight(400), stretch: Normal, italic: false, is_fallback: false, is_synthetic: false }], foreground: None }
 2021-12-19T14:47:12.550Z ERROR wezterm_gui::glyphcache                > load_glyph failed; using blank instead. Error: load_and_render_glyph: FT_Render_Glyph: FreeType error 19 0x13: cannot render this glyph format. GlyphInfo { is_space: true, cluster: 11, font_idx: 0, glyph_pos: 3, x_advance: 8.0, y_advance: 0.0, x_offset: 0.0, y_offset: 0.0 } TextStyle { font: [FontAttributes { family: "Monaco", weight: FontWeight(400), stretch: Normal, italic: false, is_fallback: false, is_synthetic: false }], foreground: None }
 2021-12-19T14:47:12.598Z ERROR wezterm_gui::glyphcache                > load_glyph failed; using blank instead. Error: load_and_render_glyph: FT_Render_Glyph: FreeType error 19 0x13: cannot render this glyph format. GlyphInfo { is_space: false, cluster: 2, font_idx: 0, glyph_pos: 29, x_advance: 8.0, y_advance: 0.0, x_offset: 0.0, y_offset: 0.0 } TextStyle { font: [FontAttributes { family: "Monaco", weight: FontWeight(400), stretch: Normal, italic: false, is_fallback: false, is_synthetic: false }], foreground: None }
 2021-12-19T14:47:12.598Z ERROR wezterm_gui::glyphcache                > load_glyph failed; using blank instead. Error: load_and_render_glyph: FT_Render_Glyph: FreeType error 19 0x13: cannot render this glyph format. GlyphInfo { is_space: false, cluster: 4, font_idx: 0, glyph_pos: 90, x_advance: 8.0, y_advance: 0.0, x_offset: 0.0, y_offset: 0.0 } TextStyle { font: [FontAttributes { family: "Monaco", weight: FontWeight(400), stretch: Normal, italic: false, is_fallback: false, is_synthetic: false }], foreground: None }
 2021-12-19T14:47:12.598Z ERROR wezterm_gui::glyphcache                > load_glyph failed; using blank instead. Error: load_and_render_glyph: FT_Render_Glyph: FreeType error 19 0x13: cannot render this glyph format. GlyphInfo { is_space: false, cluster: 5, font_idx: 0, glyph_pos: 72, x_advance: 8.0, y_advance: 0.0, x_offset: 0.0, y_offset: 0.0 } TextStyle { font: [FontAttributes { family: "Monaco", weight: FontWeight(400), stretch: Normal, italic: false, is_fallback: false, is_synthetic: false }], foreground: None }
 2021-12-19T14:47:12.599Z ERROR wezterm_gui::glyphcache                > load_glyph failed; using blank instead. Error: load_and_render_glyph: FT_Render_Glyph: FreeType error 19 0x13: cannot render this glyph format. GlyphInfo { is_space: false, cluster: 6, font_idx: 0, glyph_pos: 93, x_advance: 8.0, y_advance: 0.0, x_offset: 0.0, y_offset: 0.0 } TextStyle { font: [FontAttributes { family: "Monaco", weight: FontWeight(400), stretch: Normal, italic: false, is_fallback: false, is_synthetic: false }], foreground: None }
 2021-12-19T14:47:12.599Z ERROR wezterm_gui::glyphcache                > load_glyph failed; using blank instead. Error: load_and_render_glyph: FT_Render_Glyph: FreeType error 19 0x13: cannot render this glyph format. GlyphInfo { is_space: false, cluster: 7, font_idx: 0, glyph_pos: 87, x_advance: 8.0, y_advance: 0.0, x_offset: 0.0, y_offset: 0.0 } TextStyle { font: [FontAttributes { family: "Monaco", weight: FontWeight(400), stretch: Normal, italic: false, is_fallback: false, is_synthetic: false }], foreground: None }
 2021-12-19T14:47:12.599Z ERROR wezterm_gui::glyphcache                > load_glyph failed; using blank instead. Error: load_and_render_glyph: FT_Render_Glyph: FreeType error 19 0x13: cannot render this glyph format. GlyphInfo { is_space: false, cluster: 9, font_idx: 0, glyph_pos: 85, x_advance: 8.0, y_advance: 0.0, x_offset: 0.0, y_offset: 0.0 } TextStyle { font: [FontAttributes { family: "Monaco", weight: FontWeight(400), stretch: Normal, italic: false, is_fallback: false, is_synthetic: false }], foreground: None }
 2021-12-19T14:47:12.599Z ERROR wezterm_gui::glyphcache                > load_glyph failed; using blank instead. Error: load_and_render_glyph: FT_Render_Glyph: FreeType error 19 0x13: cannot render this glyph format. GlyphInfo { is_space: false, cluster: 10, font_idx: 0, glyph_pos: 80, x_advance: 8.0, y_advance: 0.0, x_offset: 0.0, y_offset: 0.0 } TextStyle { font: [FontAttributes { family: "Monaco", weight: FontWeight(400), stretch: Normal, italic: false, is_fallback: false, is_synthetic: false }], foreground: None }
 2021-12-19T14:47:12.599Z ERROR wezterm_gui::glyphcache                > load_glyph failed; using blank instead. Error: load_and_render_glyph: FT_Render_Glyph: FreeType error 19 0x13: cannot render this glyph format. GlyphInfo { is_space: false, cluster: 1, font_idx: 0, glyph_pos: 14, x_advance: 8.0, y_advance: 0.0, x_offset: 0.0, y_offset: 0.0 } TextStyle { font: [FontAttributes { family: "Monaco", weight: FontWeight(400), stretch: Normal, italic: false, is_fallback: false, is_synthetic: false }], foreground: None }
 2021-12-19T14:47:12.673Z TRACE wezterm_gui::termwindow                > Setting focus to true
```

> Then, please try a different font to see if this is specific to the Monaco font!

Seems like. I've tried Menlo and everything is ok.

**Comment by wez** [comment]
I don't have `Monaco.dfont` on my mac system, only `Monaco.ttf`.  Is that something you installed?  dfonts are a legacy font format and I don't think freetype or harfbuzz likes it very much; I see conflicting information in the freetype code about whether it is supported or not.

**Comment by maximko** [comment]
I think it's bundled font. Please note that I use Catalina.

**Comment by wez** [comment]
I've pushed a speculative fix for this; please try the nightly build about an hour after this comment is posted and let me know how you get on!

**Comment by maximko** [comment]
Now it looks like this:
![Screenshot 2021-12-20 at 04 45 05](https://user-images.githubusercontent.com/633363/146700261-2843efa2-e556-477f-97c8-e6ff3691fcf2.png)
So wrong size and hinting (or anti-aliasing) parameters.

**Comment by wez** [comment]
Alright, I think the heart of this is just another facet of the render bug introduced in freetype 2.11.0.
Version 2.11.1 was recently released, so I've reverted the speculative fix and the workaround and upgraded to that version.
Please give the CI ~1 hour to build out the nightly with these changes and let me know how it goes!

**Comment by maximko** [comment]
Font size is ok now, hinting (or anti-aliasing) parameters still wrong.

**Comment by wez** [comment]
Can you elaborate on what's wrong? I don't have that font and can't see what you're seeing

**Comment by maximko** [comment]
Sure. The font is not anti-aliased on non-retina display. Please see screenshots.
This is wezterm on a FullHD display:
![Screenshot 2021-12-20 at 21 45 03](https://user-images.githubusercontent.com/633363/146817468-32706388-3a70-46ac-8a16-b3950a9149a4.png)
Same window but on retina display:
<img width="1005" alt="Screenshot 2021-12-20 at 21 46 44" src="https://user-images.githubusercontent.com/633363/146817559-e4f0b9e3-658c-428f-86eb-5d6bf3c5f988.png">
iTerm2 with same 14pt Monaco font on FullHD display:

![Screenshot 2021-12-20 at 21 45 40](https://user-images.githubusercontent.com/633363/146817839-a370d682-7b3c-4e16-a552-06bdfcf555ca.png)

**Comment by wez** [comment]
I think what's happening is that the computed font size (in pixels) for the FullHD display is matching one of the pre-computed bitmap strikes that are present in the dfont; this output from `ls-fonts` shows that there are 4 bitmap fonts for those pixel sizes:

```
wezterm.font_with_fallback({
  -- /System/Library/Fonts/Monaco.dfont, CoreText
  -- Will synthesize dim
  -- Pixel sizes: [12, 13, 16, 19]
  "Monaco",
```

Bitmap fonts aren't anti-aliased when rendered, as they are simply returning the pre-built bitmaps for display purposes.

On a Retina display, the pixel density is doubled so the effective pixel size is outside the range of the pre-built bitmaps and the proportional portion of the font is used instead, and that can be anti-aliased.

I would suggest adding this to your config:

```
  freetype_load_flags = "NO_BITMAP"
```

(see https://wezfurlong.org/wezterm/config/lua/config/freetype_load_flags.html for more info)

this tells freetype to not use the bitmaps in the font and always rasterize it for itself.

**Comment by wez** [comment]
I pushed another change (please update to the latest nightly!) that allows specifying the `NO_BITMAP` flag just for the Monaco font, as setting it globally will effectively neuter emoji, which is probably not what you want.  You can also specify `harfbuzz_features` per font as well if you prefer.

Here's an example version of your config demonstrating this:

```lua
local wezterm = require 'wezterm';

local Monaco = {
  family = "Monaco",
  freetype_load_flags = "NO_BITMAP"
}

return {
  font = wezterm.font(Monaco),
  font_rules={
    {
      intensity="Bold",
      font=wezterm.font(Monaco, {
        foreground="#ffffff",
      })
    },
   -- I removed the italic entry from here, as it will be computed automatically anyway
  },
  font_size = 14.0,
  color_scheme = "iterm",
  scrollback_lines = 15000,
  tab_max_width = 32,
  harfbuzz_features = {"calt=0", "clig=0", "liga=0"},
  bypass_mouse_reporting_modifiers = "ALT",
}
```

**Comment by maximko** [comment]
Thank you, looks good now.
