### ISSUE TITLE
Config file with a BOM can't be opened

### ISSUE THREAD

**Issue by eugenesvk** [wez/wezterm#1452]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20211221-224952-1c9b9f69

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I was checking other people's configs out by pasting their content to my file manager, which created new files with the pasted content (which I renamed to `wezterm.lua` for a test)
However, I've encountered a cryptic error when launching WezTerm `syntax error: [string "..\wezterm.lua"]:1:unexpected symbol near '<\239>'`, which I later realized was referring to that pesky UTF-8 [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) that the file manager automatically added to the new files (also, I think this might be the default behavior of Notepad on Windows)

### To Reproduce

- Change the format of your `wezterm.lua` to include a [BOM](https://en.wikipedia.org/wiki/Byte_order_mark)
- Open WezTerm

### Configuration

The config file's content doesn't matter

### Expected Behavior

WezTerm should be able to discard this BOM byte on loading the files

### Anything else?

Quick googling suggested that failing on BOM might be Lua's issue (a bit surprising), though WezTerm could also help Lua by stripping it?

**Comment by wez** [comment]
UTF-8 BOMs make no sense, so I can understand where the lua folks are coming from.
http://lua-users.org/cgi-bin/namazu.cgi?query=BOM&sort=score&idxname=lua-l&max=20 shows excerpts from their mailing list going back a long way, and their resistance to sorting this out.

It's pretty trivial for wezterm to skip a BOM in the primary config file: we happen to have already loaded it into a string anyway, so I've pushed a commit that does that.

However: if you are splitting your config into multiple files and using the lua `require` function to import them, Lua itself is responsible for loading those files and will not accept the BOM.  I have no plans to do anything about that, and would generally recommend that you configure your editor to not use a BOM with UTF-8.

**Comment by eugenesvk** [comment]
> UTF-8 BOMs make no sense

and yet it still exists :( 

> It's pretty trivial for wezterm to skip a BOM in the primary config file: we happen to have already loaded it into a string anyway, so I've pushed a commit that does that.

Thanks!

> However: if you are splitting your config into multiple files and using the lua `require` function to import them, Lua itself is responsible for loading those files and will not accept the BOM. I have no plans to do anything about that, and would generally recommend that you configure your editor to not use a BOM with UTF-8.

Yeah, that's fine, and my editor is already configured this way, it's just these specific test files weren't created with an editor
