### ISSUE TITLE
Feature request: adjustable height of tab bar to help avoid terminal being covered by Macbook Pro notch

### ISSUE THREAD

**Issue by mike-hearn** [wez/wezterm#1737]
**Is your feature request related to a problem? Please describe.**
This is a pretty straight forward problem - new Apple laptops have a 64px notch right at the top of the screen, and if you fullscreen wezterm, a part of the terminal is completely hidden.

This only happens w/ the old tab bar style *and* non-native MacOS fullscreen on (both of those are, by far, my preferred way to use wezterm).

Here's a photo to demonstrate, where the notch covers the top corner of a split pane tmux window:

<img width="1382" alt="Screen Shot 2022-03-19 at 3 25 58 PM" src="https://user-images.githubusercontent.com/1016999/159135566-f2a56840-22b2-421e-ac4c-56e420bafcbb.png">

**Describe the solution you'd like**
Perhaps some kind of ability to add top, black-color padding in only full screen? Or just the ability to adjust the tab bar height (or tab bar padding)?

**Describe alternatives you've considered**
Adding padding to the top of the terminal itself works, but it's clunky because the padding isn't necessary anywhere other than fullscreen (so windowed it looks silly), and it's also not necessary on non Apple laptops, so my shared config makes the terminal look wonky on other machines.

**Additional context**
This bug is obviously not a dealbreaker, but it's just one of those QoL type of things.

Also, this terminal is great. Thank you for creating it and the work you've put into documenting it and maintaining it.

**Comment by wez** [comment]
Ah, the notch.  I think handling this overlaps a bit with https://github.com/wez/wezterm/pull/1675 
That PR is adding support for OS-dependent borders, but could be extended to add OS-dependent padding.
It sounds like https://developer.apple.com/documentation/appkit/nsscreen/3882821-safeareainsets?changes=latest_major&language=objc could be used to populate that information on macOS.

I'm leaning towards a fairly basic approach to this: in non-native fullscreen we'll use safeAreaInserts to populate the os padding parameters, then when we render, factor that in to the configured window padding.

**Comment by wez** [comment]
I pushed a commit that I think will do the job here. It should show up in a nightly build within an hour of this comment posting.

Please give it a try and let me know if it works!

If it doesn't work, please launch wezterm like this:

```
WEZTERM_LOG=window::os::macos::window=trace,info wezterm
```

and share the log output that looks like:

```
NSEdgeInsets { top: 0.0, left: 0.0, bottom: 0.0, right: 0.0 }
```

**Comment by davidrios** [comment]
I've tried the latest main, giving a thick top border on windows, and got this:

![image](https://user-images.githubusercontent.com/1418372/160271989-efd118d6-1000-48f5-9ed8-f6ff45373b38.png)

Something similar will probably happen on the Mac too.

**Comment by wez** [comment]
Yeah, I tested locally by hard-coding a top border of 32 pixel to sanity check that the content was offset reasonably, so I have confidence that it will be mostly good, provided that we correctly interpret the safe area info from macOS!

**Comment by davidrios** [comment]
No need to fix the scroll bar for this, I'm working on it now, so it'll also take the border in consideration.

**Comment by mike-hearn** [comment]
Thanks for taking a look at this so quickly.

It's almost there, I'm just seeing a couple of issues.

The first is very minor. The current padding at the top isn't quite enough. I can still see a couple of pixels-worth of notch cutting below the tab bar, but otherwise the top looks great and it makes the notch almost completely invisible. It's hidden within the black of the tab bar.

The second issue is bigger, which is that the whole terminal is pushed down, which pushes the bottom row off-screen at the bottom. In tmux I use the bottom row for pane names (e.g. `1: zsh, 2: vim, 3: python`) and that whole line is about 99% off the screen, and only a couple pixels of each letter is peeking out from the bottom.

Here's some of the log output w/ the `NSEdgeInsets` value you mentioned:

```
 2022-03-28T00:18:36.479Z WARN  wezterm_term::terminalstate::performer > Unhandled OSC  12 7
 2022-03-28T00:18:43.792Z DEBUG window::os::macos::window              > key_common: chars=`\r` unmod=`\r` modifiers=`SUPER` virtual_key=36 key_is_down:true
 2022-03-28T00:18:43.792Z TRACE window::os::macos::window              > raw key was handled; not processing further
 2022-03-28T00:18:43.798Z TRACE window::os::macos::window              > NSEdgeInsets { top: 32.0, left: 0.0, bottom: 0.0, right: 0.0 }
 2022-03-28T00:18:43.799Z TRACE window::os::macos::window              > NSEdgeInsets { top: 32.0, left: 0.0, bottom: 0.0, right: 0.0 }
 2022-03-28T00:18:43.805Z TRACE window::os::macos::window              > did_change_screen
 2022-03-28T00:18:44.137Z DEBUG window::os::macos::window              > key_common: chars=`\r` unmod=`\r` modifiers=`SUPER` virtual_key=36 key_is_down:true
 2022-03-28T00:18:44.137Z TRACE window::os::macos::window              > raw key was handled; not processing further
 2022-03-28T00:18:44.138Z TRACE window::os::macos::window              > NSEdgeInsets { top: 32.0, left: 0.0, bottom: 0.0, right: 0.0 }
 2022-03-28T00:18:44.161Z TRACE window::os::macos::window              > did_change_screen
```

**Comment by wez** [comment]
Thanks for confirming: I've factored that into the code, and I think we can call this done!  This should show up in a macOS nightly build within about an hour.
