### ISSUE TITLE
Nightly: set_config_overrides does not work with config_builder 

### ISSUE THREAD

**Issue by hunterliao29** [wez/wezterm#3079]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20230208-091928-fd5c6dce

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When config is set using config_builder,  set_config_overrides will not work.

### To Reproduce

bind set_config_overrides to a key and use it.

### Configuration

```lua
local wezterm = require("wezterm")
local config = wezterm.config_builder()

config.keys = {

	{
		key = "g",
		mods = "CTRL",
		action = wezterm.action_callback(function(window, pane)
			local overrides = window:get_config_overrides() or {}
			if not overrides.harfbuzz_features then
				-- If we haven't overridden it yet, then override with ligatures disabled
				overrides.harfbuzz_features = { "calt=0", "clig=0", "liga=0" }
			else
				-- else we did already, and we should disable out override now
				overrides.harfbuzz_features = nil
			end
			window:set_config_overrides(overrides)
		end),
	},
}
return config
```

### Expected Behavior

it should toggle ligatures

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by hunterliao29** [comment]
Work like a charm!
After testing in main, this [issue](https://github.com/wez/wezterm/discussions/3070#discussioncomment-4911204) (unable to toggle disable_default_key_bindings) is also fix when using config_builder. still does not work using Lua table.

Thank you
