### ISSUE TITLE
`wezterm imgcat` fails to display images without alpha channel

### ISSUE THREAD

**Issue by Mukundan314** [wez/wezterm#3529]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

sway

### WezTerm version

20230408-112425-69ae8472
20230415-161506-c544b0ed (nightly)

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

`wezterm imgcat` fails to display PNG images without a alpha channel.

### To Reproduce

```
curl https://0x0.st/H8Si.png -o test-image.png
wezterm imgcat test-image.png  # this does not work
magick convert test-image.png png32:test-image-fixed.png
wezterm imgcat test-image-fixed.png  # this works
```

### Configuration

no config

### Expected Behavior

The image should be displayed

### Logs

10:06:31.700 ERROR wezterm_gui::glyphcache > Error decoding image: inconsistent 224x306 -> 205632
10:06:31.715 WARN wezterm_gui::glyphcache > decoder thread terminated

### Anything else?

This problem does not occur when using kitty image protocol, with any of the transfer modes.

**Comment by wez** [comment]
This should be resolved now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by AnonymouX47** [comment]
This is among the issues I pointed out in https://github.com/wez/wezterm/issues/3263#issuecomment-1474520142 (added a couple more since the initial comment).

I'm sorry, I've been really busy since then. I'll make sure I find some time this week to check the current state of things and open separate issue for each case that still occurs and any new one I find.
