### ISSUE TITLE
bold styles not rendered in 20210404-112810-b63a949d

### ISSUE THREAD

**Issue by dmfay** [wez/wezterm#648]
I just updated and text that should be bold is now normal weight. Here's a sample, with the font changed to DejaVu Sans Mono to make sure it isn't any of the funny business I have configured on my end:

![test string showing bold and normal text looking identical](https://user-images.githubusercontent.com/3075455/113585804-b79fd500-95fa-11eb-8ffc-6ba26666f350.png)

Session: [20210405144153.tar.gz](https://github.com/wez/wezterm/files/6258692/20210405144153.tar.gz)

## Environment (please complete the following information):

 - OS: Linux lamia 5.11.11-arch1-1 #1 SMP PREEMPT Tue, 30 Mar 2021 14:10:17 +0000 x86_64 GNU/Linux
 - Version: wezterm 20210404-112810-b63a949d

**Comment by wez** [comment]
Doh, sorry about that.  I just pushed a fix for this!

**Comment by gwww** [comment]
I just downloaded latest build wezterm 20210405-110924-a5bb5be8 and not seeing bold fonts either/yet.

I took your advice and not using font with Powerline, so font may be a problem, but bold is supported. Font from here: https://fonts.google.com/specimen/Inconsolata

```
WEZTERM_LOG=wezterm_font=trace ./wezterm
 2021-04-05T21:07:38.473Z TRACE wezterm_font::shaper::harfbuzz > compute metrics across these handles for size=16, dpi=72,
             theoretical pixel height 16: [OnDisk { path: "/Users/glenn/Library/Fonts/Inconsolata-VariableFont_wdth,wght.ttf", index: 0 }, Memory { name: "../../assets/fonts/JetBrainsMono-Regular.ttf", data_len: 171876, index: 0 }, Memory { name: "../../assets/fonts/NotoColorEmoji.ttf", data_len: 7253060, index: 0 }, Memory { name: "../../assets/fonts/LastResortHE-Regular.ttf", data_len: 502504, index: 0 }]
 2021-04-05T21:07:38.473Z TRACE wezterm_font::shaper::harfbuzz > shaper wants 0 OnDisk { path: "/Users/glenn/Library/Fonts/Inconsolata-VariableFont_wdth,wght.ttf", index: 0 }
 2021-04-05T21:07:38.473Z DEBUG wezterm_font::ftwrap           > set_char_size computing 16 dpi=72 (pixel height=16)
 2021-04-05T21:07:38.475Z TRACE wezterm_font::shaper::harfbuzz > idx 0 cell_height is 16.78403401374817, which is 0.784034013748169 away from theoretical
                     height (factor 0.04900212585926056). Seems good enough
 2021-04-05T21:07:38.475Z TRACE wezterm_font::shaper::harfbuzz > metrics_for_idx=0, size=16, dpi=72 -> FontMetrics { cell_width: 8.0, cell_height: 16.78403401374817, descender: -4.0, underline_thickness: 0.8000016212463379, underline_position: -3.6000072956085205 }
 2021-04-05T21:07:38.540Z TRACE wezterm_font::shaper::harfbuzz > compute metrics across these handles for size=16, dpi=144,
             theoretical pixel height 32: [OnDisk { path: "/Users/glenn/Library/Fonts/Inconsolata-VariableFont_wdth,wght.ttf", index: 0 }, Memory { name: "../../assets/fonts/JetBrainsMono-Regular.ttf", data_len: 171876, index: 0 }, Memory { name: "../../assets/fonts/NotoColorEmoji.ttf", data_len: 7253060, index: 0 }, Memory { name: "../../assets/fonts/LastResortHE-Regular.ttf", data_len: 502504, index: 0 }]
 2021-04-05T21:07:38.540Z TRACE wezterm_font::shaper::harfbuzz > shaper wants 0 OnDisk { path: "/Users/glenn/Library/Fonts/Inconsolata-VariableFont_wdth,wght.ttf", index: 0 }
 2021-04-05T21:07:38.540Z DEBUG wezterm_font::ftwrap           > set_char_size computing 16 dpi=144 (pixel height=32)
 2021-04-05T21:07:38.541Z TRACE wezterm_font::shaper::harfbuzz > idx 0 cell_height is 33.56806802749634, which is 1.568068027496338 away from theoretical
                     height (factor 0.04900212585926056). Seems good enough
 2021-04-05T21:07:38.541Z TRACE wezterm_font::shaper::harfbuzz > metrics_for_idx=0, size=16, dpi=144 -> FontMetrics { cell_width: 16.0, cell_height: 33.56806802749634, descender:
-7.0, underline_thickness: 1.6000032424926758, underline_position: -7.200014591217041 }
 2021-04-05T21:07:38.548Z TRACE wezterm_font::rasterizer::freetype > Rasterizier wants OnDisk { path: "/Users/glenn/Library/Fonts/Inconsolata-VariableFont_wdth,wght.ttf", index: 0 }
 2021-04-05T21:07:38.549Z DEBUG wezterm_font::ftwrap               > set_char_size computing 16 dpi=144 (pixel height=32)
 2021-04-05T21:07:38.731Z TRACE wezterm_font::shaper::harfbuzz     > shaper wants 1 Memory { name: "../../assets/fonts/JetBrainsMono-Regular.ttf", data_len: 171876, index: 0 }
 2021-04-05T21:07:38.731Z DEBUG wezterm_font::ftwrap               > set_char_size computing 16 dpi=144 (pixel height=32)
 2021-04-05T21:07:38.734Z TRACE wezterm_font::rasterizer::freetype > Rasterizier wants Memory { name: "../../assets/fonts/JetBrainsMono-Regular.ttf", data_len: 171876, index: 0 }
 2021-04-05T21:07:38.734Z DEBUG wezterm_font::ftwrap               > set_char_size computing 16 dpi=144 (pixel height=32)
 2021-04-05T21:07:38.737Z TRACE wezterm_font::shaper::harfbuzz     > metrics_for_idx=1, size=16, dpi=144 -> FontMetrics { cell_width: 19.0, cell_height: 42.24008560180664, descender: -10.0, underline_thickness: 1.6000032424926758, underline_position: -5.760011672973633 }
 2021-04-05T21:08:37.453Z TRACE wezterm_font::shaper::harfbuzz     > compute metrics across these handles for size=16, dpi=144,
             theoretical pixel height 32: [OnDisk { path: "/Users/glenn/Library/Fonts/Inconsolata-VariableFont_wdth,wght.ttf", index: 0 }, Memory { name: "../../assets/fonts/JetBrainsMono-Regular.ttf", data_len: 171876, index: 0 }, Memory { name: "../../assets/fonts/NotoColorEmoji.ttf", data_len: 7253060, index: 0 }, Memory { name: "../../assets/fonts/LastResortHE-Regular.ttf", data_len: 502504, index: 0 }]
 2021-04-05T21:08:37.453Z TRACE wezterm_font::shaper::harfbuzz     > shaper wants 0 OnDisk { path: "/Users/glenn/Library/Fonts/Inconsolata-VariableFont_wdth,wght.ttf", index: 0 }
 2021-04-05T21:08:37.454Z DEBUG wezterm_font::ftwrap               > set_char_size computing 16 dpi=144 (pixel height=32)
 2021-04-05T21:08:37.457Z TRACE wezterm_font::shaper::harfbuzz     > idx 0 cell_height is 33.56806802749634, which is 1.568068027496338 away from theoretical
                     height (factor 0.04900212585926056). Seems good enough
 2021-04-05T21:08:37.457Z TRACE wezterm_font::shaper::harfbuzz     > metrics_for_idx=0, size=16, dpi=144 -> FontMetrics { cell_width: 16.0, cell_height: 33.56806802749634, descender: -7.0, underline_thickness: 1.6000032424926758, underline_position: -7.200014591217041 }
 2021-04-05T21:08:37.457Z TRACE wezterm_font::rasterizer::freetype > Rasterizier wants OnDisk { path: "/Users/glenn/Library/Fonts/Inconsolata-VariableFont_wdth,wght.ttf", index: 0 }
 2021-04-05T21:08:37.457Z DEBUG wezterm_font::ftwrap               > set_char_size computing 16 dpi=144 (pixel height=32)
 2021-04-05T21:08:48.546Z TRACE wezterm_font::shaper::harfbuzz     > shaper wants 2 Memory { name: "../../assets/fonts/NotoColorEmoji.ttf", data_len: 7253060, index: 0 }
 2021-04-05T21:08:48.546Z DEBUG wezterm_font::ftwrap               > set_char_size computing 16 dpi=144 (pixel height=32)
 2021-04-05T21:08:48.546Z DEBUG wezterm_font::ftwrap               > set_char_size: FT_Set_Char_Size

Caused by:
    FreeType error 23 0x17: invalid pixel size, will inspect strikes
 2021-04-05T21:08:48.546Z DEBUG wezterm_font::ftwrap               > idx=0 info=FT_Bitmap_Size_ { height: 128, width: 136, size: 6976, x_ppem: 6976, y_ppem: 6976 }
 2021-04-05T21:08:48.547Z TRACE wezterm_font::rasterizer::freetype > Rasterizier wants Memory { name: "../../assets/fonts/NotoColorEmoji.ttf", data_len: 7253060, index: 0 }
 2021-04-05T21:08:48.547Z DEBUG wezterm_font::ftwrap               > set_char_size computing 16 dpi=144 (pixel height=32)
 2021-04-05T21:08:48.547Z DEBUG wezterm_font::ftwrap               > set_char_size: FT_Set_Char_Size

Caused by:
    FreeType error 23 0x17: invalid pixel size, will inspect strikes
 2021-04-05T21:08:48.547Z DEBUG wezterm_font::ftwrap               > idx=0 info=FT_Bitmap_Size_ { height: 128, width: 136, size: 6976, x_ppem: 6976, y_ppem: 6976 }
 2021-04-05T21:08:48.548Z TRACE wezterm_font::shaper::harfbuzz     > metrics_for_idx=2, size=16, dpi=144 -> FontMetrics { cell_width: 136.0, cell_height: 128.0, descender: -27.0,
underline_thickness: 0.0, underline_position: 0.0 }
```
<img width="855" alt="Screen Shot 2021-04-05 at 17 13 22" src="https://user-images.githubusercontent.com/3060128/113628026-4e3bb880-9632-11eb-8662-1ceff0f7414e.png">

**Comment by dmfay** [comment]
20210405-110924-a5bb5be8 looks right for me, at least:

![1617715637](https://user-images.githubusercontent.com/3075455/113718095-4de70000-96ba-11eb-9874-98c0b30df882.png)

**Comment by gwww** [comment]
Still no luck for me. I just seconds ago downloaded the latest nightly (to be sure I had the latest). I tried two different fonts, the other one being Cascadia Mono PL. I tried under bash and zsh. I'll install the font you have and see what happens.

**Comment by gwww** [comment]
I got it to work. The Inconsolata on https://fonts.google.com/specimen/Inconsolata has two ways of installing. "Static" - which means installing regular and bold as two separate files. Or, "Variable" which installs one file which includes multiple widths and multiple "boldness" (not sure the right word for regular, bold, semi-bold, etc.).

Static versions of a font works. Variable font does not work. I will create a bug for the variable font.
