### ISSUE TITLE
Some unicode characters rendered incorrectly, with default config

### ISSUE THREAD

**Issue by JeanMertz** [wez/wezterm#849]
It appears that some(?) Unicode characters aren't properly rendering for me, even when using `wezterm -n`:

<img width="672" alt="image" src="https://user-images.githubusercontent.com/383250/120431116-55ecb480-c378-11eb-94af-9b4e2d28a3f8.png">

If you look at the dependencies list, both glyphs shown there aren't rendered as expected. Here's how those lines print in Terminal.app:

<img width="745" alt="image" src="https://user-images.githubusercontent.com/383250/120431257-8cc2ca80-c378-11eb-9d2e-fe6a4cde14cb.png">

## Environment

- OS: macOS
- Version: `wezterm 20210531-092829-7c2b30dc`

**Comment by lkhphuc** [comment]
![Screenshot 2021-06-07 at 00 45 15](https://user-images.githubusercontent.com/12573521/120943907-a160e300-c729-11eb-90d3-b936ca5fff82.png)

Same problem for me. Left is Kitty, right is wezterm with default / no config file on MacOS.

**Comment by wez** [comment]
Those glyphs are from the "Last Resort" font.  They are shown when no font containing the requested glyphs was found.

If you press `CTRL SHIFT L` wezterm should show the debug overlay which may have some information about what happened during font resolution; please share that information here.

**Comment by wez** [comment]
(press escape to close the debug overlay)

**Comment by jacobfoard** [comment]
I've also encoutered this issue, when trying to get `➛` to render I get the following error.

```
2021-06-07T15:52:19.007Z WARN  wezterm_font                   > No fonts contain glyphs for these codepoints: \u{279b}.
Placeholder 'Last Resort' glyphs are being displayed instead.
You may wish to install additional fonts, or adjust your
configuration so that it can find them.
https://wezfurlong.org/wezterm/config/fonts.html has more information about configuring fonts.
Set warn_about_missing_glyphs=false to suppress this message.
```

Same for any of the other "builtin" glyphs from macOS like `✗`.

**Comment by wez** [comment]
I can't reproduce this; `echo ✗ ✓` renders both of those glyphs.  With the default wezterm config, those glyphs are resolved from JetBrains Mono.  If you happen to have an older version of JetBrains Mono installed in the system, that font takes precedence.  Perhaps that is what is happening?

`wezterm ls-fonts` will show which fonts are being used.

@lkhphuc: it appears as though you're trying to use a symbol font that isn't part of the default font fallback list.  You will need to explicitly list the font that contains those symbols using https://wezfurlong.org/wezterm/config/lua/wezterm/font_with_fallback.html

There was an issue in resolving certain font variations on macos that I just pushed a fix for in 618f77f2c65d77720613a06b1f0a6be6af12d340 that *may* help with this, but I couldn't reproduce the issue as described either with or without that change.

Please try a nightly build (it'll take about 30 minutes from now to build out for macos) and if it isn't working, please share the output from `wezterm ls-fonts`.

**Comment by JeanMertz** [comment]
Here are some details of my output:

```
% wezterm ls-fonts
Primary font:
wezterm.font_with_fallback({
  -- /Users/jean/Library/Fonts/OperatorMonoSSmNerd-Book.otf, CoreText
  {family="Operator Mono SSm Nerd", weight="Light"},

  -- /Users/jean/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- /Users/jean/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Italic=true:
Unable to load a font matching one of your font_rules: wezterm.font('Operator Mono SSm Nerd Book Italic', {weight='Regular', stretch='Normal', italic=false}). Fallback(s) are being used instead, and the
 terminal may not render as intended. See https://wezfurlong.org/wezterm/config/fonts.html for more informationwezterm.font_with_fallback({
  -- /Users/jean/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- /Users/jean/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Bold Italic=true:
Unable to load a font matching one of your font_rules: wezterm.font('Operator Mono SSm Nerd Medium Italic', {weight='Regular', stretch='Normal', italic=false}). Fallback(s) are being used instead, and t
he terminal may not render as intended. See https://wezfurlong.org/wezterm/config/fonts.html for more informationwezterm.font_with_fallback({
  -- /Users/jean/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- /Users/jean/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Bold:
wezterm.font_with_fallback({
  -- /Users/jean/Library/Fonts/OperatorMonoSSmNerd-Medium.otf, CoreText
  {family="Operator Mono SSm Nerd", weight="DemiLight"},

  -- /Users/jean/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- /Users/jean/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Half:
wezterm.font_with_fallback({
  -- /Users/jean/Library/Fonts/OperatorMonoSSmNerd-Light.otf, CoreText
  {family="Operator Mono SSm Nerd", weight="Light"},

  -- /Users/jean/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- /Users/jean/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Half Italic=true:
wezterm.font_with_fallback({
  -- /Users/jean/Library/Fonts/OperatorMonoSSmNerd-BoldItalic.otf, CoreText
  -- Will synthesize dim
  {family="Operator Mono SSm Nerd", italic=true},

  -- /Users/jean/Library/Fonts/JetBrainsMono-Italic.ttf, CoreText
  -- Will synthesize dim
  {family="JetBrains Mono", italic=true},

  -- /Users/jean/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Will synthesize italics
  -- Will synthesize dim
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Half Italic=false:
wezterm.font_with_fallback({
  -- /Users/jean/Library/Fonts/OperatorMonoSSmNerd-Bold.otf, CoreText
  -- Will synthesize dim
  "Operator Mono SSm Nerd",

  -- /Users/jean/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  -- Will synthesize dim
  "JetBrains Mono",

  -- /Users/jean/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Will synthesize dim
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Bold Italic=false:
wezterm.font_with_fallback({
  -- /Users/jean/Library/Fonts/OperatorMonoSSmNerd-Bold.otf, CoreText
  -- Will synthesize bold
  "Operator Mono SSm Nerd",

  -- /Users/jean/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  -- Will synthesize bold
  "JetBrains Mono",

  -- /Users/jean/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Will synthesize bold
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Bold Italic=true:
wezterm.font_with_fallback({
  -- /Users/jean/Library/Fonts/OperatorMonoSSmNerd-BoldItalic.otf, CoreText
  -- Will synthesize bold
  {family="Operator Mono SSm Nerd", italic=true},

  -- /Users/jean/Library/Fonts/JetBrainsMono-Italic.ttf, CoreText
  -- Will synthesize bold
  {family="JetBrains Mono", italic=true},

  -- /Users/jean/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Will synthesize italics
  -- Will synthesize bold
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})


When Intensity=Normal Italic=true:
wezterm.font_with_fallback({
  -- /Users/jean/Library/Fonts/OperatorMonoSSmNerd-BoldItalic.otf, CoreText
  {family="Operator Mono SSm Nerd", italic=true},

  -- /Users/jean/Library/Fonts/JetBrainsMono-Italic.ttf, CoreText
  {family="JetBrains Mono", italic=true},

  -- /Users/jean/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Will synthesize italics
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})
```

I'm also not entirely sure why it says it can't load `Operator Mono SSm Nerd Book Italic`, since that font definitely exists (it is named `OperatorMonoSSmNerd-BookItalic.otf` on the file system, but Font Book.app shows it as "Operator Mono SSm Nerd Book Italic").

I did instal JetBrains Mono using `brew install font-jetbrains-mono`, which installs the latest version.

**Comment by wez** [comment]
`wezterm ls-fonts --list-system` will show you the all of the available fonts and how they are named; that may help you figure out what needs tweaking

**Comment by jacobfoard** [comment]
I can confirm that on on the latest nightly `✗` `✓` are working, but `➛` `★` aren't.

My issue seemed to be that I had previously set `font_locator = "ConfigDirsOnly"` as I was having issues getting the proper font weight to be set (which hopefully https://github.com/wez/wezterm/commit/618f77f2c65d77720613a06b1f0a6be6af12d340 resolves 😄).

Once I turned off the `font_locator` setting they rendered just fine with no logs in the debug menu.

**Comment by JeanMertz** [comment]
Okay, so I think I need some guidance here, here's what it says I have installed locally (only showing the relevant listings):

```
wezterm.font("Operator Mono SSm", weight="Light", stretch="Normal", italic=false) -- /Users/jean/Library/Fonts/OperatorMonoSSm-Book.otf, CoreText
wezterm.font("Operator Mono SSm", weight="Light", stretch="Normal", italic=false) -- /Users/jean/Library/Fonts/OperatorMonoSSm-Light.otf, CoreText
wezterm.font("Operator Mono SSm", weight="Light", stretch="Normal", italic=true) -- /Users/jean/Library/Fonts/OperatorMonoSSm-BookItalic.otf, CoreText
wezterm.font("Operator Mono SSm", weight="Light", stretch="Normal", italic=true) -- /Users/jean/Library/Fonts/OperatorMonoSSm-LightItalic.otf, CoreText
wezterm.font("Operator Mono SSm", weight="DemiLight", stretch="Normal", italic=false) -- /Users/jean/Library/Fonts/OperatorMonoSSm-Medium.otf, CoreText
wezterm.font("Operator Mono SSm", weight="DemiLight", stretch="Normal", italic=true) -- /Users/jean/Library/Fonts/OperatorMonoSSm-MediumItalic.otf, CoreText
wezterm.font("Operator Mono SSm", weight="Regular", stretch="Normal", italic=false) -- /Users/jean/Library/Fonts/OperatorMonoSSm-Bold.otf, CoreText
wezterm.font("Operator Mono SSm", weight="Regular", stretch="Normal", italic=true) -- /Users/jean/Library/Fonts/OperatorMonoSSm-BoldItalic.otf, CoreText
```

It appears _both_ `OperatorMonoSSm-Book.otf` and `OperatorMonoSSm-Light.otf` have the same family/properties, so there's no way for me to tell Wezterm which of the two to load, is that correct?

In Font Book.app I _do_ see a difference in how both are drawn. Note that these are the officially purchased fonts from Hoefler&Co, so I presume they are compiled correctly?

**Comment by JeanMertz** [comment]
Here's how it shows up in my Font Book.app:

<img width="914" alt="image" src="https://user-images.githubusercontent.com/383250/124172508-3b5a4800-daaa-11eb-9c0f-2fc372ca0d17.png">

You can see the weight differences between Book and Light.

**Comment by wez** [comment]
Hmm, yeah, I can reproduce this with Operator.  I added some debug locally:

```
wezterm.font("Operator Mono", weight="Light", stretch="Normal", italic=false) -- ot_weight=325 /Users/wez/.dotfiles/fonts/OperatorMono-Book.otf, FontDirs
wezterm.font("Operator Mono", weight="Light", stretch="Normal", italic=false) -- ot_weight=300 /Users/wez/.dotfiles/fonts/OperatorMono-Light.otf, FontDirs
```

The weight encoded in the fonts is 300 for Light and 325 for Book.

The code in wezterm buckets the weights into enum values based on this categorization:

https://github.com/wez/wezterm/blob/main/config/src/font.rs#L106-L107

I don't recall exactly where I got that mapping from, but I think that it is a bit lossy, and I think that I'll change this to hold the precise value and have some symbolic aliases.

**Comment by wez** [comment]
I believe this to be fixed in the nightly builds as a result of the changes in https://github.com/wez/wezterm/commit/423b208780af0586472bba3719fa40031f91dd82
I'm going to speculatively close this!

**Comment by JeanMertz** [comment]
I'm back on this issue after having used Kitty.app for a few months.

Unfortunately, I still have issues rendering unicode/emoji characters.

Some things to note since then:

1. I'm running version `wezterm-gui 20211108-075740-a6da9568` (latest nightly as of this writing).
2. I _don't_ have "Noto Color Emoji" installed, since it isn't supported on macOS.
3. I'm using "Heavy Ballot X" Unicode character `U+2718` for testing purposes.
4. It renders correctly in Firefox (`✘`)
5. I've expanded my `wezterm.lua` to use the following `font_with_fallback` function:
   
   ```lua
   local fonts = {}
   fonts["Operator Mono SSm Light"]         = { family = "Operator Mono Ssm Lig", weight = 275 }
   fonts["Operator Mono SSm Light Italic"]  = { family = "Operator Mono Ssm Lig", weight = 275, italic = true }
   fonts["Operator Mono SSm Book"]          = { family = "Operator Mono Ssm Lig", weight = 325 }
   fonts["Operator Mono SSm Book Italic"]   = { family = "Operator Mono Ssm Lig", weight = 325, italic = true }
   fonts["Operator Mono SSm Medium"]        = { family = "Operator Mono Ssm Lig", weight = "DemiLight" }
   fonts["Operator Mono SSm Medium Italic"] = { family = "Operator Mono Ssm Lig", weight = "DemiLight", italic = true }
   fonts["Operator Mono SSm Bold"]          = { family = "Operator Mono Ssm Lig", weight = "Regular" }
   fonts["Operator Mono SSm Bold Italic"]   = { family = "Operator Mono Ssm Lig", weight = "Regular", italic = true }

   function font_with_fallback(name)
     local names = {
       fonts[name],
       { family = "Apple Color Emoji" },
       { family = "JetBrains Mono" },
       { family = "SF Mono" },
       { family = "San Francisco" },
       { family = "sans-serif" },
     }

     return wezterm.font_with_fallback(names)
   end
   ```

   I tested that this function is called as expected, since removing the first `fonts[name]` does change the font used for rendering.

6. Here's the output of `./test-data/emoji-presentation.sh` (spoiler: no icons are shown):

   <img width="421" alt="image" src="https://user-images.githubusercontent.com/383250/140819709-13afcf2c-c955-4ae1-b8e2-f7886518cbc5.png">

7. Here's the output of `brew info nvim`, which contains the `✘` unicode character:

   <img width="823" alt="image" src="https://user-images.githubusercontent.com/383250/140819845-1e04ef9e-cd78-4112-87e7-734dbb73ac4d.png">

8. The above produces the following error:

   ```
   > No fonts contain glyphs for these codepoints: \u{2718}.
   Placeholder 'Last Resort' glyphs are being displayed instead.
   You may wish to install additional fonts, or adjust your configuration so that it can find them.
   https://wezfurlong.org/wezterm/config/fonts.html has more information about configuring fonts.
   Set warn_about_missing_glyphs=false to suppress this message.
   ```

8. Here's when I copy `✘` into Wezterm:

   <img width="157" alt="image" src="https://user-images.githubusercontent.com/383250/140819945-655786bc-e84c-4b4d-aa10-0914169441e0.png">

9. Here's what happens when I do `wezterm ls-fonts --text "😀︎"`

   <img width="887" alt="image" src="https://user-images.githubusercontent.com/383250/140820186-23940065-c613-43d3-ae68-a0dd9cffad41.png">

   So, it appears it's still trying to use `Noto Color Emoji`, even though I haven't defined that as a fallback (It does mention it's a built-in fallback, and indeed it does show an emoji, so I'm guessing it doesn't matter whether I have it installed or not). I would have expected that at least _one_ of the fallback fonts I listed would have correctly shown the smiley, especially "Apple Color Emoji", yet this doesn't appear to be the case.

10. Here's the same for `wezterm ls-fonts --text "✘︎"`

   <img width="955" alt="image" src="https://user-images.githubusercontent.com/383250/140820558-262a9b6d-71ce-4554-874d-12822ea0a9ba.png">

I hope this gives you a clue as to what is going on. I'm at a loss why I'm having so much issues with font rendering, whereas it appears almost no-one else is having similar issues on macOS (or no one is noticing/reporting).

**Comment by JeanMertz** [comment]
Here's an updated `./test-data/emoji-presentation.sh`, and its output:

```fish
#!/usr/local/bin/fish

printf "\u270c  Victory hand, text presentation by default\n"
printf "\u270c\ufe0e  Victory hand, explicit text presentation\n"
printf "\u270c\ufe0f  Victory hand, explicit emoji presentation\n"
printf "\n"
printf "\u270a  Raised fist, emoji presentation by default\n"
printf "\u270a\ufe0e  Raised fist, explicit text presentation\n"
printf "\u270a\ufe0f  Raised fist, explicit emoji presentation\n"
```

<img width="373" alt="image" src="https://user-images.githubusercontent.com/383250/140822769-797e4f24-c91d-485f-a170-a2f3095b9019.png">

**Comment by wez** [comment]
@JeanMertz interesting.  There are a couple of issues coming together here:

* `Menlo` is the font that contains those ballot glyphs, but Menlo, despite being the genesis of our system fallback lookup, isn't itself included in the fallback list
* `ls-fonts` doesn't know to wait for the asynchronous system fallback to complete, so it stops at the first pass

I just pushed 1ec7e10c19a6d5497c549dde2607a19d020b3f13 which addresses both of those concerns.

You can either wait for this to show up in a nightly build, or add `Menlo` to your `font_with_fallback` call to get those glyphs in the meantime.

**Comment by JeanMertz** [comment]
Awesome, thanks.

Two somewhat related questions:

1. How can one build the macOS binary from source? I've built the CLI binaries many times before, but never quite figured out how to build the `WezTerm.app` package. I'm hesitant to copy/paste the CLI binaries into the package, as I'm not certain if there are other changes I need to make to the package contents to have it correctly use the latest built binaries.

2. Out of curiosity, how did you figure out that `Menlo` is the only font that included that glyph? I tried searching for the glyph in `Font Book.app`, but it only searches for font names, not included glyphs.

**Comment by JeanMertz** [comment]
The heavy cross sign now works as expected 🎉 . I'm still seeing a difference between Kitty and WezTerm for other icons, though:

<img width="1536" alt="Screenshot 2021-11-09 at 08 04 17" src="https://user-images.githubusercontent.com/383250/140877604-95907371-184d-46dd-a191-8539b3deb07e.png">

I'm going to try and figure out from which font those are taken in the case of Kitty.app, and see if adding them to my list of fallback fonts solves the problem.

**Comment by JeanMertz** [comment]
I also still wonder if it's possible to use `Apple Color Emoji` for emoji rendering. I've got it configured in my fallback fonts, but it still renders emojis using `Noto Color Emoji`, which is somewhat off-putting, as it's different from all other emoji rendering on my system.

```
When Intensity=Normal:
wezterm.font_with_fallback({
  -- /Users/jean/Library/Fonts/OperatorMonoSSmLig-Book.otf, CoreText
  {family="Operator Mono SSm Lig", weight=325},

  -- /System/Library/Fonts/Apple Color Emoji.ttc index=1 variation=0, CoreText
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [23, 30, 37, 47, 56, 61, 75, 113, 188]
  ".Apple Color Emoji UI",

  -- /Users/jean/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- /Users/jean/Library/Fonts/JetBrainsMono-Regular.ttf, CoreText
  "JetBrains Mono",

  -- <built-in>, BuiltIn
  -- Assumed to have Emoji Presentation
  -- Pixel sizes: [128]
  "Noto Color Emoji",

  -- <built-in>, BuiltIn
  "Last Resort High-Efficiency",

})
```

<img width="886" alt="image" src="https://user-images.githubusercontent.com/383250/140879830-1d22e593-0a7a-4e8c-97a1-b839ef775941.png">

**Comment by JeanMertz** [comment]
It's interesting seeing [other people](https://github.com/wez/wezterm/issues/1039#issue-973202053) also specifying `Apple Color Emoji` as a fallback font, so I'm assuming it's working for them.

**Comment by JeanMertz** [comment]
Ah, interesting:

<img width="911" alt="image" src="https://user-images.githubusercontent.com/383250/140915033-200a991a-239a-4044-bd03-86ec02473811.png">

What happened in that first test is that I used my terminal history from before I had configured the Apple emoji as a fallback, then hit backspace to remove the old Google smiley, then I pasted in the Apple one, but it got swapped out by the Google one.

In the second attempt, I re-typed the entire command, and pasted in the Apple one, and it stayed in place.

So, I'm assuming my 1-backspace action removed the emoji, but left some kind of hidden character in place that caused the pasted in Apple emoji to be swapped to the Google one?

It might be confusing, but I guess it's the way it is with multi-character unicode tokens, etc.

**Comment by wez** [comment]
> 2\. Out of curiosity, how did you figure out that `Menlo` is the only font that included that glyph? I tried searching for the glyph in `Font Book.app`, but it only searches for font names, not included glyphs.

I laboriously went through fonts in Font Book with the heavy cross entered in the preview mode until I found a font that had that glyph :-/

**Comment by wez** [comment]
> Ah, interesting:
> 
> <img alt="image" width="911" src="https://user-images.githubusercontent.com/383250/140915033-200a991a-239a-4044-bd03-86ec02473811.png">
> 
> What happened in that first test is that I used my terminal history from before I had configured the Apple emoji as a fallback, then hit backspace to remove the old Google smiley, then I pasted in the Apple one, but it got swapped out by the Google one.
> 
> In the second attempt, I re-typed the entire command, and pasted in the Apple one, and it stayed in place.
> 
> So, I'm assuming my 1-backspace action removed the emoji, but left some kind of hidden character in place that caused the pasted in Apple emoji to be swapped to the Google one?
> 
> It might be confusing, but I guess it's the way it is with multi-character unicode tokens, etc.

I can't fully explain what's happening there, as it doesn't reproduce for me, but the background is that the first example you pasted `U+1F644 U+FE0E` is a sequence that says `FACE WITH ROLLING EYES` with explicit text presentation (`U+FE0E` is `VS15` which indicates text presentation).

There isn't a formal thing that indicates if a font provides text or emoji presentation for its glyphs, so wezterm uses a simple two-phase heuristic based on the font family name; if it contains `Emoji` then the `Assumed to have Emoji Presentation` flag is set for the font.  At shaping time, if the requested glyph's presentation is explicitly set to text then the first pass font match will not match the glyph against the `Assumed to have Emoji Presentation` fonts and then a second pass will be made with the explicit text presentation cleared.  That second pass should then match against your selected emoji font.

For me, using this stripped down config:

```lua
local wezterm = require 'wezterm'

return {
  font_size = 14.0,
  font = wezterm.font_with_fallback({"JetBrains Mono", "Apple Color Emoji"})
}
```

I get:

```
; ./target/debug/wezterm --config-file /tmp/wat.lua ls-fonts --text "$(echo -e 🙄\\ufe0e)"
🙄︎   \u{1f644}\u{fe0e} glyph=2057 wezterm.font(".Apple Color Emoji UI", {weight="Regular", stretch="Normal", italic=false})
                             /System/Library/Fonts/Apple Color Emoji.ttc index=1 variation=0, CoreText

; ./target/debug/wezterm --config-file /tmp/wat.lua ls-fonts --text "$(echo -e 🙄\\ufe0f)"
🙄️   \u{1f644}\u{fe0f} glyph=2057 wezterm.font(".Apple Color Emoji UI", {weight="Regular", stretch="Normal", italic=false})
                             /System/Library/Fonts/Apple Color Emoji.ttc index=1 variation=0, CoreText

; ./target/debug/wezterm --config-file /tmp/wat.lua ls-fonts --text "$(echo -e 🙄)"
🙄    \u{1f644}    glyph=2057 wezterm.font(".Apple Color Emoji UI", {weight="Regular", stretch="Normal", italic=false})
                             /System/Library/Fonts/Apple Color Emoji.ttc index=1 variation=0, CoreText
```

Note that when I run those ls-fonts from my current, older, build of wezterm, I see this:

![image](https://user-images.githubusercontent.com/117777/140951123-6943c5ec-2636-4857-b193-160521f54bc5.png)

but if I run it from inside the updated build I see this:

![image](https://user-images.githubusercontent.com/117777/140951028-a1c5fb83-6d31-497b-b9ee-c10112d8832b.png)

So I wonder if you're sometimes running the older build, or a wezterm with a different configuration (perhaps you need to force a config reload?) for some of your experimentation?
